//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favs {
            get {
                return ResourceManager.GetString("Favs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 3 (three) favorite players..
        /// </summary>
        internal static string InfoSelFavPlayers {
            get {
                return ResourceManager.GetString("InfoSelFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a favorite team..
        /// </summary>
        internal static string InfoSelFavTeam {
            get {
                return ResourceManager.GetString("InfoSelFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and region.
        /// </summary>
        internal static string LangAndReg {
            get {
                return ResourceManager.GetString("LangAndReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match statistics.
        /// </summary>
        internal static string MatchStats {
            get {
                return ResourceManager.GetString("MatchStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player statistics.
        /// </summary>
        internal static string PlayerStats {
            get {
                return ResourceManager.GetString("PlayerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wish to exit?.
        /// </summary>
        internal static string PromptExit {
            get {
                return ResourceManager.GetString("PromptExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save favorites.
        /// </summary>
        internal static string SaveFavs {
            get {
                return ResourceManager.GetString("SaveFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select favorite players:.
        /// </summary>
        internal static string SelFavPlayers {
            get {
                return ResourceManager.GetString("SelFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select favorite team:.
        /// </summary>
        internal static string SelFavTeam {
            get {
                return ResourceManager.GetString("SelFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup gender.
        /// </summary>
        internal static string WCGender {
            get {
                return ResourceManager.GetString("WCGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup.
        /// </summary>
        internal static string WorldCup {
            get {
                return ResourceManager.GetString("WorldCup", resourceCulture);
            }
        }
    }
}
