//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resource {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resource() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resource", typeof(Resource).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Attendance.
    /// </summary>
    public static string Attendance {
        get {
            return ResourceManager.GetString("Attendance", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Away Team.
    /// </summary>
    public static string AwayTeam {
        get {
            return ResourceManager.GetString("AwayTeam", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cancel.
    /// </summary>
    public static string Cancel {
        get {
            return ResourceManager.GetString("Cancel", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Confirm exit.
    /// </summary>
    public static string ConfirmExit {
        get {
            return ResourceManager.GetString("ConfirmExit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Controls.
    /// </summary>
    public static string Controls {
        get {
            return ResourceManager.GetString("Controls", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Croatian.
    /// </summary>
    public static string Croatian {
        get {
            return ResourceManager.GetString("Croatian", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Date/Time.
    /// </summary>
    public static string DateTime {
        get {
            return ResourceManager.GetString("DateTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to English.
    /// </summary>
    public static string English {
        get {
            return ResourceManager.GetString("English", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Favorites.
    /// </summary>
    public static string Favs {
        get {
            return ResourceManager.GetString("Favs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Goals.
    /// </summary>
    public static string Goals {
        get {
            return ResourceManager.GetString("Goals", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Help.
    /// </summary>
    public static string Help {
        get {
            return ResourceManager.GetString("Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Home Team.
    /// </summary>
    public static string HomeTeam {
        get {
            return ResourceManager.GetString("HomeTeam", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Image.
    /// </summary>
    public static string Image {
        get {
            return ResourceManager.GetString("Image", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot have more than 3 favorite players..
    /// </summary>
    public static string InfoLimitReached3FavPlayers {
        get {
            return ResourceManager.GetString("InfoLimitReached3FavPlayers", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select at least 1 (one) favorite player..
    /// </summary>
    public static string InfoSelFavPlayers {
        get {
            return ResourceManager.GetString("InfoSelFavPlayers", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select a favorite team..
    /// </summary>
    public static string InfoSelFavTeam {
        get {
            return ResourceManager.GetString("InfoSelFavTeam", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Language and region.
    /// </summary>
    public static string LangAndReg {
        get {
            return ResourceManager.GetString("LangAndReg", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Match statistics.
    /// </summary>
    public static string MatchStats {
        get {
            return ResourceManager.GetString("MatchStats", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Men.
    /// </summary>
    public static string Men {
        get {
            return ResourceManager.GetString("Men", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Player.
    /// </summary>
    public static string Player {
        get {
            return ResourceManager.GetString("Player", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Player Name.
    /// </summary>
    public static string PlayerName {
        get {
            return ResourceManager.GetString("PlayerName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Player statistics.
    /// </summary>
    public static string PlayerStats {
        get {
            return ResourceManager.GetString("PlayerStats", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Print.
    /// </summary>
    public static string Print {
        get {
            return ResourceManager.GetString("Print", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Do you really wish to exit?.
    /// </summary>
    public static string PromptExit {
        get {
            return ResourceManager.GetString("PromptExit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Quit.
    /// </summary>
    public static string Quit {
        get {
            return ResourceManager.GetString("Quit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save.
    /// </summary>
    public static string Save {
        get {
            return ResourceManager.GetString("Save", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save favorites.
    /// </summary>
    public static string SaveFavs {
        get {
            return ResourceManager.GetString("SaveFavs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select favorite players:.
    /// </summary>
    public static string SelFavPlayers {
        get {
            return ResourceManager.GetString("SelFavPlayers", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select favorite team:.
    /// </summary>
    public static string SelFavTeam {
        get {
            return ResourceManager.GetString("SelFavTeam", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    public static string Settings {
        get {
            return ResourceManager.GetString("Settings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Venue.
    /// </summary>
    public static string Venue {
        get {
            return ResourceManager.GetString("Venue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to World Cup gender.
    /// </summary>
    public static string WCGender {
        get {
            return ResourceManager.GetString("WCGender", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Women.
    /// </summary>
    public static string Women {
        get {
            return ResourceManager.GetString("Women", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to World Cup.
    /// </summary>
    public static string WorldCup {
        get {
            return ResourceManager.GetString("WorldCup", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Yellow Cards.
    /// </summary>
    public static string YellowCards {
        get {
            return ResourceManager.GetString("YellowCards", resourceCulture);
        }
    }
}
